### ISSUE TITLE
TRAP_BEG/TRAP_END undefined

### ISSUE THREAD

**Issue by diclophis** [brianmario/mysql2#608]
Hello,

This gem fails to install when using ruby-2.2.1... I believe the issue is directly related to the removal of the `TRAP_BEG/TRAP_END` definitions:

See: https://bugs.ruby-lang.org/projects/ruby-trunk/wiki/CAPI_obsolete_definitions

	Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
	
	    /Users/mavenlink/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20150406-15895-1emq7sn.rb extconf.rb
	checking for rb_thread_blocking_region()... no
	checking for rb_wait_for_single_fd()... yes
	checking for rb_hash_dup()... yes
	checking for rb_intern3()... yes
	checking for mysql.h... yes
	checking for errmsg.h... yes
	checking for mysqld_error.h... yes
	creating Makefile
	
	make "DESTDIR=" clean
	
	make "DESTDIR="
	compiling client.c
	In file included from client.c:1:
	In file included from ./mysql2_ext.h:39:
	In file included from ./client.h:11:
	/Users/mavenlink/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/backward/rubysig.h:14:2: warning: rubysig.h is obsolete [-W#warnings]
	#warning rubysig.h is obsolete
	 ^
	In file included from client.c:1:
	In file included from ./mysql2_ext.h:39:
	./client.h:13:14: warning: redefinition of typedef 'rb_unblock_function_t' is a C11 feature [-Wtypedef-redefinition]
	typedef void rb_unblock_function_t(void *);
	             ^
	/Users/mavenlink/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/intern.h:897:14: note: previous definition is here
	typedef void rb_unblock_function_t(void *);
	             ^
	In file included from client.c:1:
	In file included from ./mysql2_ext.h:39:
	./client.h:14:15: warning: redefinition of typedef 'rb_blocking_function_t' is a C11 feature [-Wtypedef-redefinition]
	typedef VALUE rb_blocking_function_t(void *);
	              ^
	/Users/mavenlink/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/intern.h:898:15: note: previous definition is here
	typedef VALUE rb_blocking_function_t(void *);
	              ^
	In file included from client.c:1:
	In file included from ./mysql2_ext.h:39:
	./client.h:23:3: error: use of undeclared identifier 'TRAP_BEG'
	  TRAP_BEG;
	  ^
	./client.h:25:3: error: use of undeclared identifier 'TRAP_END'
	  TRAP_END;
	  ^
	client.c:1056:56: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'unsigned int' [-Wshorten-64-to-32]
	  mysql2rb = mysql2_mysql_enc_name_to_rb(charset_name, charset_name_len);
	             ~~~~~~~~~~~~~~~~~~~~~~~~~~~               ^~~~~~~~~~~~~~~~
	4 warnings and 2 errors generated.
	make: *** [client.o] Error 1
	
	make failed, exit code 2
	
	Gem files will remain installed in /Users/mavenlink/.rvm/gems/ruby-2.2.1@stats/gems/mysql2-0.3.12 for inspection.
	Results logged to /Users/mavenlink/.rvm/gems/ruby-2.2.1@stats/extensions/x86_64-darwin-13/2.2.0/mysql2-0.3.12/gem_make.out
	An error occurred while installing mysql2 (0.3.12), and Bundler cannot continue.
	Make sure that `gem install mysql2 -v '0.3.12'` succeeds before bundling.

**Comment by sodabrew** [comment]
This was fixed in #415 almost two years ago. Please use a newer version of the mysql2 gem; I looked in the git history and version 0.3.14 is the minimum version required for Ruby 2.0+ compatibility.

**Comment by diclophis** [comment]
@sodabrew thanks for the quick turn around on responding to my issue... I fear though that the problem still persists in the latest version of this gem. Please note the presence of these tokens in this file on the master branch: https://github.com/brianmario/mysql2/blob/master/ext/mysql2/client.h#L29

**Comment by sodabrew** [comment]
It's ok, the older code is wrapped in a macro; this is designed for compatibility across several versions of Ruby.

**Comment by rakeshyadavitan** [comment]
@sodabrew thank you for the solution.
